syntax = "proto3";

package wallet;

option go_package = "./walletpb";

message StoreWalletRequest {
  string mnemonic = 1;
  string ticker = 2;
  string public_key = 3;
  string private_key = 4;
  string address = 5;
  uint32 index = 6;
  string passphrase_hash = 7; // Store hash for security
  string created_by = 8;
}

message StoreWalletResponse {
  bool success = 1;
  string message = 2;
  int64 wallet_id = 3;
}

service WalletService {
  rpc StoreWallet(StoreWalletRequest) returns (StoreWalletResponse);
}